language: java
jdk:
- openjdk7
sudo: required
before_script:
- cd $HOME
- sudo apt-get install -y git git-core
- curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
- echo "export PATH=~/bin:$PATH" >> ~/.bashrc ; source ~/.bashrc
- mkdir twrp && cd twrp
- git config --global user.name "yshalsager"
- git config --global user.email ysh-alsager@hotmail.com
script:
- repo init -u git://github.com/yshtemp/twrp.git -b cm-twrp-5.1-norepo --depth=1
- repo sync -c -f -j64 --force-sync --no-clone-bundle --no-tags
- rm -rf .repo
- du -sh .
- export today=$(date +"%Y%m%d")
- XZ_OPT=-e9 tar cJf - $HOME/twrp/ -P | pv -s $(du -sb $HOME/twrp/ | awk '{print $1}') | gzip > cm_twrp-5.1.1-$today.tar.xz
- ls -h -l *.tar.xz ; du -h *.tar.xz

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  file: "$HOME/twrp/cm_twrp-5.1.1-$today-norepo.tar.xz"
  on:
    tags: false
    repo: yshtemp/twrp
    branch: cm-twrp-5.1-norepo
